### PR TITLE
feat: add property to receive Link component in command

### PR DESCRIPTION
**Pull request by yazaldefilimonepinto**
Hi there,

I've added a new feature to the menu command library for React. Previously, it only supported HTML links for navigation, but I've added the ability to pass a Next.js Link component as a property.

This change should make it easier for users of the library who are working with Next.js to integrate the menu command into their projects.

Please let me know if there are any changes or improvements that need to be made.

exemple to use with `Link`  next component : 
```tsx
{
      category: 'Links',
      commands: [
        {
          icon: <FiGithub />,
          text: 'Source Code',
          keywords: 'GitHub',
          shortcuts: { keys: ['g', 'h'] },
          href: 'https://github.com/harshhhdev/kmenu',
          Anchor: ({ children, ...props }) => (
            <Link {...props}>
              {children}
            </Link>
            
          ),
          newTab: true
        }....
```

Thank you,
[Yazalde Filimone](https://github.com/yazaldefilimonepinto)

### CODE REVIEW

**Review by harshhhdev — CHANGES_REQUESTED** [review]
Thanks for the PR! This is a great idea, and it looks good to me for the most part. I've updated some things like the spacing/comments/capitalization to the proper TypeScript/JSDoc standard, but other than that everything looks good.

The only issue here is that you this repo is a couple of commits behind master. I'd be happy to merge + document it afterwards too.

**Comment by harshhhdev** [comment]
This is going on release v1.3 along with #90. Aiming for a release today.

**Comment by harshhhdev** [comment]
do ping me again when you're ready for another review

**Comment by yazaldefilimonepinto** [comment]
> do ping me again when you're ready for another review

Hello, thank you for the feedback! I have updated my branch and it seems to be on the same version as the master. However, I would like to clarify that I don't speak English fluently and I'm not fully understanding what you mean. Could you please explain in more detail about the problem related to the commits?

**Comment by harshhhdev** [comment]
Sorry fort he delay @yazaldefilimonepinto.
I'll just merge this in and update it myself. Thanks for the contribution 💓

**Pull request merged**
